spring:

  datasource:
    url: jdbc:h2:mem:climalert

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: santiagoezequielherrera2003@gmail.com
    password: ysnw ryxl jdgp tzqz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

weather:
  api-key: 04068e7f25874896843135850260507
